app:
  image:
    tag: ""
  secrets:
    external:
      remotePrefix: "/k8s/stg-m4n4"
  ingress:
    hosts:
      - host: "pr-194-governance.stg.aepps.com"
        paths:
          - path: "/"
            version: "pr-194"
      - host: "pr-193-governance.stg.aepps.com"
        paths:
          - path: "/"
            version: "pr-193"
      - host: "pr-195-governance.stg.aepps.com"
        paths:
          - path: "/"
            version: "pr-195"
      - host: "pr-196-governance.stg.aepps.com"
        paths:
          - path: "/"
            version: "pr-196"
      - host: "pr-197-governance.stg.aepps.com"
        paths:
          - path: "/"
            version: "pr-197"
      - host: "pr-198-governance.stg.aepps.com"
        paths:
          - path: "/"
            version: "pr-198"
      - host: "governance.stg.aepps.com"
        paths:
          - path: "/"
            version: "master"
  versions:
    - version: "pr-194"
      gitSha: "f6dd305"
    - version: "pr-193"
      gitSha: "b716fa5"
    - version: "pr-195"
      gitSha: "f61070e"
    - version: "pr-196"
      gitSha: "e60eeac"
    - version: "pr-197"
      gitSha: "2b0df28"
    - version: "pr-198"
      gitSha: "04c4055"
    - version: "master"
      gitSha: "ef33afe"
