app:
  image:
    tag: ""
  secrets:
    external:
      remotePrefix: "/k8s/stg-m4n4"
  ingress:
    hosts:
      - host: "pr-194-governance.stg.aepps.com"
        paths:
          - path: "/"
            version: "pr-194"
      - host: "governance.stg.aepps.com"
        paths:
          - path: "/"
            version: "master"
  versions:
    - version: "pr-194"
      gitSha: "f6dd305"
    - version: "master"
      gitSha: "9e35642"
