app:
  image:
    tag: "master"
    pullPolicy: "Always"
  ingress:
    enabled: true
    annotations:
      traefik.ingress.kubernetes.io/router.entrypoints: websecure
      cert-manager.io/cluster-issuer: letsencrypt
  service:
    port: 3000
  resources:
    requests:
      memory: 350Mi
    limits:
      memory: 500Mi
  secrets:
    external:
      values:
        BRIDGE_OWNER_PK: /apps/HC_BRIDGE_OWNER_PK
        BRIDGE_USER_PK: /apps/HC_BRIDGE_USER_PK
        PG_PASSWORD: /apps/HC_POSTGRES_PASSWORD
  env:
    PG_HOST: "aepp-hyperchain-bridge-postgresql"
    PG_PORT: "5432"
    PG_DATABASE: "hyperchain_bridge"
    PG_USER: "hyperchain_bridge"
    PG_SSL: "false"

postgresql:
  enabled: false
  auth:
    username: "hyperchain_bridge"
    database: "hyperchain_bridge"
  primary:
    persistence:
      enabled: true
      size: 5Gi
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 384Mi
