app:
  image:
    tag: ""
    repository: "public.ecr.aws/aeternity/aepp-faucet-nodejs"
  secrets:
    external:
      remotePrefix: "/k8s/stg-m4n4"
  ingress:
    hosts:
      - host: "pr-49-faucet.stg.aepps.com"
        paths:
          - path: "/"
            version: "pr-49"
      - host: "pr-48-faucet.stg.aepps.com"
        paths:
          - path: "/"
            version: "pr-48"
      - host: "faucet.stg.aepps.com"
        paths:
          - path: "/"
            version: "master"
  versions:
    - version: "pr-49"
      gitSha: "e2e9c4b"
    - version: "pr-48"
      gitSha: "6d8730e"
    - version: "master"
      gitSha: "e621fa8"
