app:
  image:
    tag: ""
    repository: "public.ecr.aws/aeternity/aepp-faucet-nodejs"
  secrets:
    external:
      remotePrefix: "/k8s/stg-m4n4"
  ingress:
    hosts:
      - host: "pr-49-faucet.stg.aepps.com"
        paths:
          - path: "/"
            version: "pr-49"
      - host: "pr-48-faucet.stg.aepps.com"
        paths:
          - path: "/"
            version: "pr-48"
      - host: "pr-50-faucet.stg.aepps.com"
        paths:
          - path: "/"
            version: "pr-50"
      - host: "pr-51-faucet.stg.aepps.com"
        paths:
          - path: "/"
            version: "pr-51"
      - host: "pr-52-faucet.stg.aepps.com"
        paths:
          - path: "/"
            version: "pr-52"
      - host: "faucet.stg.aepps.com"
        paths:
          - path: "/"
            version: "master"
  versions:
    - version: "pr-49"
      gitSha: "e2e9c4b"
    - version: "pr-48"
      gitSha: "6d8730e"
    - version: "pr-50"
      gitSha: "0589fe9"
    - version: "pr-51"
      gitSha: "0f515b4"
    - version: "pr-52"
      gitSha: "6a98e81"
    - version: "master"
      gitSha: "f84f6b8"
