app:
  image:
    tag: ""
    repository: "public.ecr.aws/aeternity/aepp-contracts"
  ingress:
    hosts:
      - host: "pr-149-contracts.stg.aepps.com"
        paths:
          - path: "/"
            version: "pr-149"
      - host: "contracts.stg.aepps.com"
        paths:
          - path: "/"
            version: "master"
      - host: "pr-150-contracts.stg.aepps.com"
        paths:
          - path: "/"
            version: "pr-150"
      - host: "pr-148-contracts.stg.aepps.com"
        paths:
          - path: "/"
            version: "pr-148"
  versions:
    - version: "pr-149"
      gitSha: "7613732"
    - version: "master"
      gitSha: "c3ef7a7"
    - version: "pr-150"
      gitSha: "c1e006f"
    - version: "pr-148"
      gitSha: "1e6650c"
