app:
  image:
    tag: ""
    repository: "public.ecr.aws/aeternity/aepp-contracts"
  ingress:
    hosts:
      - host: "pr-149-contracts.stg.aepps.com"
        paths:
          - path: "/"
            version: "pr-149"
      - host: "pr-148-contracts.stg.aepps.com"
        paths:
          - path: "/"
            version: "pr-148"
      - host: "pr-150-contracts.stg.aepps.com"
        paths:
          - path: "/"
            version: "pr-150"
      - host: "pr-151-contracts.stg.aepps.com"
        paths:
          - path: "/"
            version: "pr-151"
      - host: "contracts.stg.aepps.com"
        paths:
          - path: "/"
            version: "master"
  versions:
    - version: "pr-149"
      gitSha: "7613732"
    - version: "pr-148"
      gitSha: "1e6650c"
    - version: "pr-150"
      gitSha: "78af24b"
    - version: "pr-151"
      gitSha: "7d133e7"
    - version: "master"
      gitSha: "a64982f"
